CPh.Vape/Models/Evaluation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CPh.Vape.Models
{
    public class Evaluation
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
        public int Quality { get; set; }
        [Display(Name = "Price Changes")]
        public int PriceChanges { get; set; }
        public int Delivery { get; set; }
        public int Service { get; set; }
        public int Serial { get; set; }
        public DateTime Date { get; set; }
        public string Comments { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual User Preparer { get; set; }
        public virtual ICollection<Checker> Checkers { get; set; }
        public virtual ICollection<Approver> Approvers { get; set; }
        [Display(Name = "Evaluation Type")]
        public EvaluationType EvaluationType { get; set; }
        public ProductType Product { get; set; }
        public EvaluationCriterion EvaluationCriterion { get; set; }
        public bool Locked { get; set; }
        [Display(Name = "Review Period")]
        public ReviewFrequency ReviewFreq { get; set; }
        [Display(Name = "Evaluation Year")]
        public int EvaluationYear { get; set; }

        public enum ProductType
        {
            [Display(Name = "IT Hardware / Software Product")]
            ItProduct,
            [Display(Name = "IT Service")]
            ItService,
            [Display(Name = "Non-IT Product")]
            NonItProduct,
            [Display(Name = "Non-IT Service")]
            NonItService
        }

        public enum ReviewFrequency
        {
            [Display(Name = "1st")]
            First,
            [Display(Name = "2nd")]
            Second
        }
    }
}

CPh.Vape/Controllers/ApproversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CPh.Vape.Models;
using CPh.Vape.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace CPh.Vape.Controllers
{
    [Authorize]
    public class ApproversController : Controller
    {
        private readonly VapeDbContext _context;

        public ApproversController(VapeDbContext context)
        {
            _context = context;
        }

        // GET: Approvers/Create
        public async Task<IActionResult> Create(Guid id)
        {
            var approvers = await _context.Users.ToListAsync();
            var viewModel = new ApproverViewModel
            {
                ApproversList = approvers,
                EvaluationId = id
            };
            return View(viewModel);
        }

        // POST: Approvers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ApproverViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var approver = new Approver
                {
                    Evaluation = await _context.Evaluations.SingleAsync(x => x.Id == viewModel.EvaluationId),
                    User = await _context.Users.SingleAsync(x => x.Id == viewModel.SelectedApproverId)
                };
                _context.Add(approver);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Evaluations", new { id = approver.Evaluation.Id });
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var approver = await _context.Approvers.SingleOrDefaultAsync(m => m.Id == id);
            await _context.Entry(approver).Reference(x => x.Evaluation).LoadAsync();
            var evaluationId = approver.Evaluation.Id;
            _context.Approvers.Remove(approver);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Evaluations", new { id = evaluationId });
        }

        private bool ApproverExists(Guid id)
        {
            return _context.Approvers.Any(e => e.Id == id);
        }
    }
}

CPh.Vape/Controllers/CheckersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CPh.Vape.Models;
using CPh.Vape.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace CPh.Vape.Controllers
{
    [Authorize]
    public class CheckersController : Controller
    {
        private readonly VapeDbContext _context;

        public CheckersController(VapeDbContext context)
        {
            _context = context;
        }

        // GET: Checkers/Create
        public async Task<IActionResult> Create(Guid id)
        {
            var checkers = await _context.Users.ToListAsync();
            var viewModel = new CheckersViewModel
            {
                CheckersList = checkers,
                EvaluationId = id
            };

            return View(viewModel);
        }

        // POST: Checkers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CheckersViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var checker = new Checker
                {
                    Evaluation = await _context.Evaluations.SingleAsync(x => x.Id == viewModel.EvaluationId),
                    User = await _context.Users.SingleAsync(x => x.Id == viewModel.SelectedCheckerId)
                };
                _context.Add(checker);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Evaluations", new { id = checker.Evaluation.Id });
            }
            return View(viewModel);
        }
        
        public async Task<IActionResult> Delete(Guid id)
        {
            var checker = await _context.Checkers.SingleOrDefaultAsync(m => m.Id == id);
            await _context.Entry(checker).Reference(x => x.Evaluation).LoadAsync();
            var evaluationId = checker.Evaluation.Id;
            _context.Checkers.Remove(checker);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Evaluations", new { id = evaluationId });
        }

        private bool CheckerExists(Guid id)
        {
            return _context.Checkers.Any(e => e.Id == id);
        }
    }
}

CPh.Vape/Controllers/EvaluationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CPh.AdQuery.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CPh.Vape.Models;
using CPh.Vape.ViewModels;
using Microsoft.AspNetCore.Authorization;
using OfficeOpenXml;
using System.IO;
using System.Text;

namespace CPh.Vape.Controllers
{
    [Authorize]
    public class EvaluationsController : Controller
    {
        private readonly VapeDbContext _context;

        public EvaluationsController(VapeDbContext context)
        {
            _context = context;
        }

        // GET: Evaluations
        public async Task<IActionResult> Index()
        {
            var list = await _context.Evaluations
                .Include(x => x.Vendor)
                .Include(x => x.EvaluationType)
                .ToListAsync();
            return View(list);
        }

        // GET: Evaluations/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var evaluations = _context.Evaluations.Include(x => x.Preparer).Include(x => x.Vendor)
                .Include(x => x.Checkers).ThenInclude(x => x.User)
                .Include(x => x.Approvers).ThenInclude(x => x.User)
                .Include(x => x.EvaluationType);
            var evaluation = await evaluations.Where(x => x.Id == id).SingleOrDefaultAsync();

            if (evaluation == null)
            {
                return NotFound();
            }

            return View(evaluation);
        }

        // GET: Evaluations/Create
        public async Task<IActionResult> Create()
        {
            var vendorList = await _context.Vendors.ToListAsync();
            var evaluationTypesList = await _context.EvaluationTypes.Select(x => new SelectListItem
            {
                Text = x.Description,
                Value = x.Id.ToString()
            }).ToListAsync();

            var viewModel = new EvaluationCreateViewModel
            {
                VendorList = vendorList,
                EvaluationTypeList = evaluationTypesList
            };
            return View(viewModel);
        }

        // POST: Evaluations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EvaluationCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var globalId = User.UserDetails().Name;
                var currentUser = await _context.Users.SingleOrDefaultAsync(m => m.GlobalId == globalId);
                int serial = 1;
                if (await _context.Evaluations.AnyAsync())
                {
                    serial = await _context.Evaluations.MaxAsync(x => x.Serial) + 1;
                }

                var evaluationType = await _context.EvaluationTypes.SingleOrDefaultAsync(m => m.Id == viewModel.SelectedEvaluationTypeId);

                var evaluation = new Evaluation
                {
                    Vendor = await _context.Vendors.SingleOrDefaultAsync(m => m.Id == viewModel.SelectedVendorId),
                    Comments = viewModel.Comments,
                    Delivery = viewModel.Delivery,
                    PriceChanges = viewModel.PriceChanges,
                    Quality = viewModel.Quality,
                    Service = viewModel.Service,
                    Preparer = currentUser,
                    Date = DateTime.Now,
                    Serial = serial,
                    Product = viewModel.ProductType,
                    EvaluationType = evaluationType,
                    EvaluationYear = viewModel.EvaluationYear,
                    ReviewFreq = viewModel.ReviewFrequency
                };

                var evaluationCriterion = new EvaluationCriterion
                {
                    Evaluation = evaluation,
                    DeliveryPercent = evaluationType.DeliveryPercent,
                    PriceChangesPercent = evaluationType.PriceChangesPercent,
                    QualityPercent = evaluationType.QualityPercent,
                    ServicePercent = evaluationType.ServicePercent
                };

                evaluation.EvaluationCriterion = evaluationCriterion;

                _context.Evaluations.Add(evaluation);
                _context.EvaluationCriteria.Add(evaluationCriterion);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { id = evaluation.Id });
            }
            return View(viewModel);
        }

        // GET: Evaluations/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluation = await _context.Evaluations.SingleOrDefaultAsync(m => m.Id == id);
            if (evaluation == null)
            {
                return NotFound();
            }

            var evaluationTypesList = await _context.EvaluationTypes.Select(x => new SelectListItem
            {
                Text = x.Description,
                Value = x.Id.ToString()
            }).ToListAsync();

            var viewModel = new EvaluationEditViewModel
            {
                Comments = evaluation.Comments,
                Delivery = evaluation.Delivery,
                EvaluationTypeList = evaluationTypesList,
                EvaluationYear = evaluation.EvaluationYear,
                Id = evaluation.Id,
                PriceChanges = evaluation.PriceChanges,
                ProductType = evaluation.Product,
                Quality = evaluation.Quality,
                ReviewPeriod = evaluation.ReviewFreq,
                Service = evaluation.Service
            };

            return View(viewModel);
        }

        // POST: Evaluations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, EvaluationEditViewModel viewModel)
        {
            if (id != viewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var evaluation = await _context.Evaluations.Where(x => x.Id == id).SingleAsync();

                    evaluation.EvaluationYear = viewModel.EvaluationYear;
                    evaluation.EvaluationType = await _context.EvaluationTypes.FindAsync(viewModel.SelectedEvaluationTypeId);
                    evaluation.Product = viewModel.ProductType;
                    evaluation.ReviewFreq = viewModel.ReviewPeriod;
                    evaluation.Quality = viewModel.Quality;
                    evaluation.PriceChanges = viewModel.PriceChanges;
                    evaluation.Delivery = viewModel.Delivery;
                    evaluation.Service = viewModel.Service;
                    evaluation.Comments = viewModel.Comments;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EvaluationExists(viewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        // GET: Evaluations/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluation = await _context.Evaluations
                .SingleOrDefaultAsync(m => m.Id == id);
            if (evaluation == null)
            {
                return NotFound();
            }

            return View(evaluation);
        }

        // POST: Evaluations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            var evaluation = await _context.Evaluations
                .Include(x => x.Approvers)
                .Include(x => x.Checkers)
                .Include(x => x.Preparer)
                .SingleOrDefaultAsync(x => x.Id == id);
            _context.Evaluations.Remove(evaluation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Download(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluations = _context.Evaluations
                .Include(x => x.Approvers).ThenInclude(x => x.User)
                .Include(x => x.Checkers).ThenInclude(x => x.User)
                .Include(x => x.Preparer)
                .Include(x => x.Vendor).ThenInclude(x => x.Contact)
                .Include(x => x.EvaluationType)
                .Include(x => x.EvaluationCriterion);
            var evaluation = await evaluations.SingleOrDefaultAsync(x => x.Id == id);

            if (evaluation == null)
            {
                return NotFound();

CPh.Vape/Views/Evaluations/Create.cshtml
@using CPh.Vape.Models
@model CPh.Vape.ViewModels.EvaluationCreateViewModel
@{
    ViewData["Title"] = "Create";
}
<h2>Create</h2>
<h4>Evaluation</h4>
<hr />
<form asp-action="Create">
    <div class="row">
        <div class="col-md-12">
            <label asp-for="SelectedVendorId" class="control-label"></label>
            <span asp-validation-for="SelectedVendorId" class="text-danger"></span>
            <table class="table">
                <thead>
                <tr>
                    <th></th>
                    <th>Vendor Code</th>
                    <th>Name</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var vendor in Model.VendorList)
                {
                    <tr>
                        <td><input type="radio" asp-for="SelectedVendorId" value="@vendor.Id" /></td>
                        <td>@vendor.VendorCode</td>
                        <td>@vendor.Name</td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EvaluationYear" class="control-label"></label>
                <select asp-for="EvaluationYear" class="form-control"></select>
                <span asp-validation-for="EvaluationYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SelectedEvaluationTypeId" class="control-label"></label>
                <select asp-for="SelectedEvaluationTypeId" asp-items="@Model.EvaluationTypeList" class="form-control"></select>
                <span asp-validation-for="SelectedEvaluationTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductType" class="control-label"></label>
                <select asp-for="ProductType" asp-items="@Html.GetEnumSelectList<Evaluation.ProductType>()" class="form-control"></select>
                <span asp-validation-for="ProductType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReviewFrequency" class="control-label"></label>
                <select asp-for="ReviewFrequency" asp-items="@Html.GetEnumSelectList<Evaluation.ReviewFrequency>()" class="form-control"></select>
                <span asp-validation-for="ReviewFrequency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quality" class="control-label"></label>
                <input asp-for="Quality" class="form-control" />
                <span asp-validation-for="Quality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceChanges" class="control-label"></label>
                <input asp-for="PriceChanges" class="form-control" />
                <span asp-validation-for="PriceChanges" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Delivery" class="control-label"></label>
                <input asp-for="Delivery" class="form-control" />
                <span asp-validation-for="Delivery" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service" class="control-label"></label>
                <input asp-for="Service" class="form-control" />
                <span asp-validation-for="Service" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <textarea asp-for="Comments" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @{await Html.RenderPartialAsync("_DataTablesCreateInit");}
    <script type="text/javascript" src="~/js/year-select.js"></script>
    <script type="text/javascript">
        var yearNow = new Date().getFullYear();
        $('#EvaluationYear').yearselect({
            start: yearNow - 5,
            end: yearNow,
            order: 'desc'
        });
    </script>
}

CPh.Vape/Views/Evaluations/Delete.cshtml
@model CPh.Vape.Models.Evaluation

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Evaluation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quality)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quality)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PriceChanges)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PriceChanges)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Delivery)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Service)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Service)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EvaluationType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EvaluationType.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CPh.Vape/Views/Evaluations/Details.cshtml
@model CPh.Vape.Models.Evaluation

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>
<span class="pull-right"><a asp-action="Download" asp-route-id="@Model.Id" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-download-alt" aria-hidden="true"></i> Download</a></span>

<div>
    <h4>Evaluation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Serial)
        </dt>
        <dd>
            @($"VPE-{Model.Serial:000000}")
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vendor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vendor.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @($"{Model.Date:D}")
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quality)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quality)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PriceChanges)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PriceChanges)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Delivery)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Delivery)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Service)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Service)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EvaluationType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EvaluationType.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EvaluationYear)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EvaluationYear)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReviewFreq)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReviewFreq)
        </dd>

    </dl>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <span style="font-weight: bold">Prepared By</span>
            </div>
            <div class="panel-body">
                @Html.DisplayFor(model => model.Preparer.Name)
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <span style="font-weight: bold">Checked By</span>
                <div class="pull-right">
                    <a class="btn btn-danger btn-xs" asp-action="Create" asp-controller="Checkers" asp-route-id="@Model.Id">Add New</a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-condensed">
                    @foreach (var checker in Model.Checkers)
                    {
                        <tr>
                            <td>
                                @checker.User.Name
                            </td>
                            <td>
                                <a asp-controller="Checkers" asp-action="Delete" asp-route-id="@checker.Id"><i class="glyphicon glyphicon-trash pull-right" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <span style="font-weight: bold">Approved By</span>
                <div class="pull-right">
                    <a class="btn btn-danger btn-xs" asp-action="Create" asp-controller="Approvers" asp-route-id="@Model.Id">Add New</a>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-condensed">
                    @foreach (var approver in Model.Approvers)
                    {
                        <tr>
                            <td>
                                @approver.User.Name
                            </td>
                            <td>
                                <a asp-controller="Approvers" asp-action="Delete" asp-route-id="@approver.Id"><i class="glyphicon glyphicon-trash pull-right" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>


CPh.Vape/Views/Evaluations/Index.cshtml
@model IEnumerable<CPh.Vape.Models.Evaluation>

@{
    ViewData["Title"] = "Index";
}

<h2>Vendor Evaluations</h2>

<p>
    <a asp-action="Create" class="btn btn-info">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Serial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vendor.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EvaluationType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EvaluationYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReviewFreq)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">@($"VPE-{item.Serial:D6}")</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vendor.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EvaluationType.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EvaluationYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReviewFreq)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_DataTablesInit");
    }
}